#!/usr/bin/env python3
"""Synchronize immutable-capture manifests into PDN source records and inventory.

This deliberately does NOT promote a source to VERIFIED_FOR_EXTRACTION. It only
records evidence that bytes from the registered official route were captured
byte-exactly and fingerprinted.

For publication-ID manifests, source-identity proof is mandatory: publication IDs
must have been taken from the source document section, and the official API number
must match a registered federal-law source number when that check applies.

Registered canonical-route captures that do not use a publication ID are validated
by their own route/content proof instead. The current consolidated 152-FZ additionally
requires proof that the returned bytes contain the amendment marker of the pinned
current revision (No. 265-FZ, effective 26.07.2026).
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "security-corpora" / "RU" / "152-FZ"
MANIFEST_DIR = CORPUS / "manifests"
INVENTORY = CORPUS / "PDN_MASTER_SOURCE_INVENTORY.yaml"
FEDERAL_LAW_NUMBER_RE = re.compile(r"^\d+-ФЗ$")
CURRENT_ROOT_SOURCE_ID = "SEC-SRC-RU-152FZ-2026-07-26"
PP687_SOURCE_ID = "SEC-SRC-RU-PP687-2008"


def q(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def manifest_is_raw_verified(manifest: dict) -> bool:
    proof = manifest.get("proof", {})
    schema_version = str(manifest.get("schema_version") or "")
    capture_kind = str(manifest.get("capture_kind") or "")
    source_id = str(manifest.get("source_id") or "")

    # Grandfather the first byte-exact official-PDF manifests already accepted
    # before identity-scope proof fields existed.
    if schema_version == "1.0":
        return bool(
            proof.get("pdf_signature_ok")
            and proof.get("byte_length_matches_official_api")
            and proof.get("sha256_calculated_from_downloaded_bytes")
        )

    if not (
        proof.get("official_route")
        and proof.get("byte_exact_download")
        and proof.get("sha256_calculated_from_downloaded_bytes")
    ):
        return False

    # PP687 uses a pre-registered official canonical route and does not acquire by
    # publication ID. Validate the route and strong content markers instead of
    # requiring the publication-ID scope flag that is not applicable to this path.
    if capture_kind == "official_registered_route_snapshot":
        return bool(
            source_id == PP687_SOURCE_ID
            and proof.get("registered_route_used")
            and proof.get("publication_api_length_check_not_applicable")
            and proof.get("canonical_content_identity_markers_ok")
            and manifest.get("semantic_status_unchanged")
        )

    # Publication-PDF and generic canonical manifests generated by the shared
    # acquirer must prove that any acquisition identity was scoped to the source
    # document itself, not inherited from nested amendment/version-chain metadata.
    if schema_version >= "1.2":
        if not proof.get("publication_id_scoped_to_source_document_section"):
            return False
        source_number = str(manifest.get("source_document_number") or "").strip()
        if FEDERAL_LAW_NUMBER_RE.fullmatch(source_number):
            if not proof.get("official_api_number_matches_source_document_when_checkable"):
                # Current consolidated canonical snapshots have no publication API
                # number to compare. They are gated below by content/version proof.
                if capture_kind != "official_canonical_snapshot":
                    return False

    if capture_kind == "official_publication_pdf":
        return bool(proof.get("pdf_signature_ok") and proof.get("byte_length_matches_official_api"))

    if capture_kind == "official_canonical_snapshot":
        if not proof.get("publication_api_length_check_not_applicable"):
            return False
        if source_id == CURRENT_ROOT_SOURCE_ID:
            return bool(
                proof.get("canonical_content_identity_markers_ok")
                and proof.get("current_revision_marker_ok")
                and proof.get("current_revision_trigger") == "265-ФЗ"
                and proof.get("current_revision_effective_from") == "2026-07-26"
                and manifest.get("semantic_status_unchanged")
            )
        return True

    return False


def update_source(manifest: dict) -> None:
    path = ROOT / manifest["source_record_ref"]
    text = path.read_text(encoding="utf-8")
    kind = manifest.get("capture_kind", "official_publication_pdf")
    note = (
        "Byte-exact official PDF captured; overall source status remains METADATA_VERIFIED until extraction/source-locator review gates pass."
        if kind == "official_publication_pdf"
        else "Byte-exact snapshot from the registered official canonical URL captured; overall source status remains METADATA_VERIFIED until semantic/version-locator review gates pass."
    )
    block = (
        "capture:\n"
        f"  raw_artifact_ref: {q(manifest['artifact_ref'])}\n"
        f"  manifest_ref: {q(str((MANIFEST_DIR / (manifest['source_id'] + '.json')).relative_to(ROOT)).replace(chr(92), '/'))}\n"
        f"  capture_kind: {q(kind)}\n"
        f"  source_url: {q(manifest.get('source_url') or manifest.get('official_file_url'))}\n"
        f"  retrieved_at: {q(manifest['retrieved_at'])}\n"
        f"  mime: {q(manifest['mime'])}\n"
        f"  byte_length: {int(manifest['byte_length'])}\n"
        f"  sha256: {q(manifest['sha256'])}\n"
        "  fingerprint_status: IMMUTABLE_CAPTURED\n"
        "  semantic_status: UNCHANGED\n"
        f"  note: {q(note)}\n"
    )
    updated, count = re.subn(
        r"(?ms)^capture:\n.*?(?=^[A-Za-z_][A-Za-z0-9_]*:|\Z)", block + "\n", text, count=1
    )
    if count != 1:
        raise RuntimeError(f"capture block not found in {path}")
    path.write_text(updated, encoding="utf-8")


def inventory_source_ids(text: str) -> list[str]:
    return re.findall(r"(?m)^  - id:\s*([^\s#]+)\s*$", text)


def update_inventory(manifests: list[dict]) -> None:
    text = INVENTORY.read_text(encoding="utf-8")
    captured = {m["source_id"] for m in manifests}
    all_ids = inventory_source_ids(text)
    for source_id in sorted(captured):
        pat = re.compile(rf"(?ms)(^  - id: {re.escape(source_id)}\n.*?^    raw_capture:)\s*[^\n]+")
        text, n = pat.subn(r"\1 IMMUTABLE_CAPTURED", text, count=1)
        if n != 1:
            raise RuntimeError(f"inventory source block not found for {source_id}")

    for source_id in all_ids:
        if source_id in captured:
            continue
        pat = re.compile(rf"(?ms)(^  - id: {re.escape(source_id)}\n.*?^    raw_capture:)\s*[^\n]+")
        text, _ = pat.subn(r"\1 PENDING", text, count=1)

    total = len(all_ids)
    immutable = len(captured.intersection(all_ids))
    pending_ids = [sid for sid in all_ids if sid not in captured]
    replacements = {
        "raw_downloaded_exact": immutable,
        "immutable_sha256_verified": immutable,
        "pending_raw_capture": len(pending_ids),
    }
    for key, value in replacements.items():
        text, n = re.subn(rf"(?m)^(  {re.escape(key)}:)\s*[^\n]+$", rf"\1 {value}", text, count=1)
        if n != 1:
            raise RuntimeError(f"counter not found: {key}")

    ratio = (immutable / total) if total else 0.0
    if "raw_capture_coverage_ratio:" in text:
        text = re.sub(
            r"(?m)^  raw_capture_coverage_ratio:\s*[^\n]+$", f"  raw_capture_coverage_ratio: {ratio:.4f}", text
        )
    else:
        anchor = re.search(r"(?m)^  source_registration_success_rate:.*$", text)
        if anchor:
            pos = anchor.end()
            text = text[:pos] + f"\n  raw_capture_coverage_ratio: {ratio:.4f}" + text[pos:]

    if pending_ids:
        blocker = (
            "acquisition_blockers:\n"
            "  - >-\n"
            "      Official byte-exact acquisition is operational through publication-ID PDFs and registered canonical official URLs.\n"
            "      Remaining source IDs without an accepted immutable manifest: " + ", ".join(pending_ids) + ".\n\n"
        )
        first_gate = "  - capture and fingerprint the remaining official raw artifacts\n"
    else:
        blocker = (
            "acquisition_blockers:\n"
            "  - >-\n"
            "      None at the raw-acquisition layer for the registered PDN core: every inventory source has an accepted immutable manifest.\n"
            "      Semantic extraction and source-locator review remain separate gates.\n\n"
        )
        first_gate = ""

    text, n = re.subn(r"(?ms)^acquisition_blockers:\n.*?(?=^next_gate:)", blocker, text, count=1)
    if n != 1:
        raise RuntimeError("acquisition_blockers section not found")

    next_gate = (
        "next_gate:\n"
        + first_gate
        + "  - structural parse and legal/semantic chunking of immutable captures\n"
        "  - concept/definition reconciliation and conflict detection\n"
        "  - atomic requirement extraction with source locators\n"
        "  - typed inter-document relations, regression fixtures and review gates\n"
    )
    text, n = re.subn(r"(?ms)^next_gate:\n.*\Z", next_gate, text, count=1)
    if n != 1:
        raise RuntimeError("next_gate section not found")

    INVENTORY.write_text(text, encoding="utf-8")


def main() -> None:
    manifests = [json.loads(p.read_text(encoding="utf-8")) for p in sorted(MANIFEST_DIR.glob("*.json"))]
    manifests = [m for m in manifests if manifest_is_raw_verified(m)]
    for manifest in manifests:
        update_source(manifest)
    update_inventory(manifests)
    print(json.dumps({"captured": len(manifests), "source_records_synced": len(manifests)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
